#!/bin/bash
set -o errexit

SOURCE=$1

if [ -z "$SOURCE" ]
then
  echo "Please specify a source directory"
  exit -1
fi

if [ ! -d "$SOURCE" ]
then
  echo "Specified directory does not exist"
  exit -1
fi

# Import common stuff
rsync -aC "$SOURCE/common" algobase
echo "Imported common files"
mkdir -p "algobase/include"
echo '#include "try.h"' > "algobase/include/randombytes.h"
echo "Created randombytes.h"

function import_op(){
	if [ ! -d "$SOURCE/crypto_${1}" ]
	then
		echo "Source directory does not contain a crypto_${1} directory"
	else
		rsync -aC "$SOURCE/crypto_${1}" algobase
		echo "Imported $SOURCE/crypto_${1}"
	fi
}

import_op verify 
import_op core 
import_op aead
import_op kem
import_op sign
