#!/bin/bash

# what platform
#platform="msp430fg4618_4mhz"
#platform="atmega644_16mhz"
#platform="atmega644_8mhz"
#platform="atmega1281_16mhz"
#platform="sample"
#platform="artila_m501"
#platform=ek-tm4c123gxl_16mhz
#platform=pc_linux
platform=msp-exp430f5529lp_16mhz

# compile again, although binaries exist? 
# (absent => 1)
recompile=1

# enable to use only first working compiler/options pair and not every one
# creates at max one binary per implementation
# useful for fast runs or testing
# (absent => 0)
only_one_binary=0


# To get algorithms to benchmark the following steps are neccessary:
# download and extract algorithm packs and/or supercop
# use ./import_algopack <dir> to import each algopack and/or supercop


# enable to compile/benchmark only a specific hash
#onlyhash="0hash"
#onlyhash="cubehash816"
#onlyhash="skein512"
#onlyhash="edonr256"
#onlyhash="shabal512"
#onlyhash="shavite3256"
#onlyhash="shavite3512"
#onlyhash="bmw256"
#onlyhash="whirlpool"
#onlyhash="echo256"
#onlyhash="edonr256"
#onlyhash="fugue256"
#onlyhash="essence224"
#onlyhash="hamsi"
#onlyhash="keccakr1024c576"
#onlyhash="keccak"
#onlyhash="simd256"
#onlyhash="groestl256"
#onlyhash="blake32"
onlyhash="keccakc512"
#onlyhash="skein256"
#onlyhash="jh256"

# ignore implementations matching this patters
#implIgnorePattern="^(asm64)|(sse)|(openssl)|(mmx)|(emmintrin)|(cryptopp)|(pentium4)|(athlon64)"

implIgnorePattern="^(avr8)|(avr8asmc)|(avr8asmf)|(compact)|(compact8)|(gil)|(inplace-armv7a-neon)|(inplace)|(inplace32bi-armv6m)|(inplace32bi-armv7a)|(inplace32bi-armv7m)|(inplace32bi)|(mmxu1)|(opt32bi-rvku2)|(opt32)|(opt32bi-s2lcu4)|(opt32biT-s2lcu4)|(opt64lcu24)|(opt64lcu24shld)|(opt64lcu6)|(opt64u6)|(simple32bi)|(sphlib-small)|(sphlib)|(sseu2)|(x86_64_asm)|(x86_64_shld)|(xopu24)"


# set to nonempy to use rsync for copying (ignoring .svn directories)
fromsvn=

# The algorithm base is where all algorithms to benchmark are located
# change this if you want to use multiple algorithm bases
# note: the import_algopack script always imports to "algobase"
algobase="algobase"


# activate to use ccache
CCACHE=ccache

# ---- end of user options --- 

