#define XBX_LITTLE_ENDIAN
#define CONSTDATAAREA

#define PAGESIZE 256
#define FLASH_ADDR_MAX (0xffffff)
#define PAGE_ALIGN_MASK 0xffffff00
#define PLATFORM_STACK_SIZE (8192)

#define DEVICE_SPECIFIC_SANE_TC_VALUE 1000000000 
#define TC_VALUE_SEC 1.0

//#define IP_COMM 1
//#define DEVICE_SPECIFIC_IPCOMM_DELAY 12500

