#!/bin/bash

isTool=1



. lib/settingsreader    

if [ -z $1 ]  || [ -z $2 ]
then
  echo "$0 CIPHER XBH-IP [XBH-Port]"
  exit -1
fi
 
exec 5> >(gnuplot -geometry 800x700) 
 
xbhIp=`echo $2 | tr -cd '[a-z][A-Z][0-9][\._\-]'`;

if [ -z "$3" ]
then
  xbhPort=22595
  else
  xbhPort=`echo $3 | tr -cd '[0-9]'`;
fi
    

function shortenCompilerWord
{
  local c=$1
  echo $c | sed -r 's/^(.{0,8}cc).*(O.*$)/\1 \2/' | sed 's/_/ /g'
}


resultdir="$XBPATH/bench/${platform}_${xbhIp}_${xbhPort}"
rcipher=$1
if [ ! -d "$resultdir" ]
then
  echo "No results in $resultdir"
  exit -2
fi


i=0
previmpl=
while read line
do  
  type=`echo $line | cut -d " " -f 7`
  if [ "$type" == "try" ]
  then
    read cipher checksumOk benchmarkcycles checksumcycles implementation compiler  < <(echo $line | cut -d " " -f 6,9,10,11,13,14)
    [ "$cipher" == "$rcipher" ] || continue
    compiler=$(shortenCompilerWord $compiler)
    implementation=`echo $implementation | sed 's/^.*crypto_hash\/[^\/]*\///'`;
    if [ $i == 0 ]
    then
      echo 'set term x11 enhanced font "arial,15"' >&5 
      echo 'set style data boxes' >&5
      echo 'set boxwidth 0.4' >&5
      echo 'set format "%.0f"' >&5
      echo 'set mouse' >&5
      echo 'set xtics (" " 50)' >&5
      echo 'set yrange [0:]' >&5
      echo 'set key left below' >&5
      echo "set title \"Quick Benchmark Results For $cipher\"" >&5
      echo "set ylabel \"Cycles for benchmark run\"" >&5
      echo set grid >&5
      echo -n "plot '<echo $i $benchmarkcycles' u 1:2 w boxes fs solid title \"{/=8($benchmarkcycles) $implementation $compiler}\"" >&5
      previmpl=$implementation
    else
      if [ "$previmpl" != "$implementation" ]
      then
        i=$(( $i + 1 ))
      fi
      echo -n ", '<echo $i $benchmarkcycles' u 1:2 w boxes fs solid title \"{/=8($benchmarkcycles) $implementation $compiler}\"" >&5
    fi
    i=$(( $i + 1 ))
    previmpl=$implementation
  
  fi
done  < <(cat "$resultdir/data" | grep -E "^[^+].* try.*")

if [ $i == 0 ]
then
  echo "No data found"
  exit -1
fi
echo >&5

echo "pause 3600" >&5

